---
- name: Ensure New Relic integrations folder exists
  file:
    path: /etc/newrelic-infra/integrations.d
    state: directory
    mode: "0755"

- name: Configure Memcached integration
  template:
    src: memcached-config.yml.j2
    dest: /etc/newrelic-infra/integrations.d/memcached-config.yml
    mode: "0644"

- name: Run New Relic integration health check for Memcached
  shell: sudo /usr/bin/newrelic-infra -dry_run -integration_config_path /etc/newrelic-infra/integrations.d/memcached-config.yml | grep -wo "Integration health check finished with success"
  register: newrelic_health_check_output
  ignore_errors: yes

- name: Check New Relic integration health check result for Memcached
  fail:
    msg: "New Relic integration health check for Memcached failed"
  when: "'Integration health check finished with success' not in newrelic_health_check_output.stdout"
